### ISSUE TITLE
How to upgrade  if  FACT  installed via docker?

### ISSUE THREAD

**Issue by jdhellfire** [fkie-cad/FACT_core#1125]
### Feature description

How to upgrade  if  FACT  installed via docker?

**Comment by maringuu** [comment]
Hi, sorrt to come back to you so late. This is actually the same issue as https://github.com/fkie-cad/FACT_docker/issues/40.
Sadly the answer is, that you currently cannot. If you find the time to try upgrading (as described in https://github.com/fkie-cad/FACT_docker/issues/40) we would very much appreciate if you report your observations.
