### ISSUE TITLE
Bottleneck in upload process, seemingly within uWSGI

### ISSUE THREAD

**Issue by harmansmithandsons** [fkie-cad/FACT_core#1144]
### The FACT version you are using

6cb9354d6ea5160bc56374485db42608ac1b4424

### Your question

I'm currently running version 4.3 on Ubuntu 22.04, in a VMWare VM with 12 GiB ram, 5 processors, and 40 GiB of disk space.

When working with moderately large files (500 MiB - 1 Gib) I've observed a major bottleneck in getting a file uploaded into FACT, well before any analyses take place, on the scale of 2.5 hours for a 1 GiB filesystem. 

I've done some of my own sleuthing to try and find out where this holdup is happening, and it looks like the issue lies somewhere in the act of getting the backend all the data. I added some print statements and timestamps within `./src/web_interface/components/io_routes.py` to see what functions might be causing the holdup: 

![image](https://github.com/fkie-cad/FACT_core/assets/147437037/bd259d69-f973-4e65-9f90-9827180a83d6)

I've collected some logs with these print lines. The below logs are taken from trying to upload an arbitrary 1 GiB filesystem made through buildroot, which I can share if interested:

```
-----
2023-09-25 09:31:30.467716 BEGINNING POST UPLOAD
-----

2023-09-25 09:31:30.467781 BEGINNING create_analysis_task
2023-09-25 09:31:30.467834 inside create_analysis_task

[...]
[...]
[...]

2023-09-25 10:51:40.033421 got meta_from_request
2023-09-25 10:51:41.258997 got binary from request
2023-09-25 10:51:41.822617 got uid of task
2023-09-25 10:51:41.822673 FINISHING create_ analysis_task

2023-09-25 10:51:41.822703 BEGINNING convert_analysis_to_fw_obj
2023-09-25 10:51:44.209959 FINISHING convert_analysis_task_to_fw_obj

2023-09-25 10:51:44.210020 BEGINNING add_analysis_task
2023-09-25 10:51:46.507327 FINISHING add_analysis_task

-----
2023-09-25 10:51:46.507380 FINISHING POST UPLOAD
-----
```

I found it strange that it would execute parts of the HTTP route, but then hang for a couple hours. It appears that the hanging starts whenever the route tries to do anything with the `request` object, such as accessing `request.form['device_name']`. Once we are able to do one of these accesses, though, we're clearly able to do everything immediately after as well.

I'm interested in knowing whatever suspicions you might have about this. Could it be that data getting *into* uWSGI is a bottleneck, or some computation *within* it prevents the data from being passed along to the endpoint? I would appreciate your thoughts. Thank you, as well!

**Comment by jstucke** [comment]
Hi and thank you for reporting this. It looks pretty strange. I tried to reproduce it with a ~350MB file but `create_analysis_task()` was finished in ~0.8 seconds. What version of uwsgi, werkzeug and flask do you have installed? Which browser are you using? Is FACT running on the same device or are you submitting the file over the network (could it be an issue with a virtual network of the VM)?

Sooner or later there will probably be a memory issue though: FACT is a notorious memory hog because the files get duplicated in memory during concurrent analysis (probably not during upload, though).

**Comment by harmansmithandsons** [comment]
I'm working with:
- uWSGI 2.0.22
- werkzeug 2.3.4
- Flask 2.3.2
- Chrome
- FACT is running on the same device, `localhost:5000`

I am currently running a similarly sized upload (400mb) to have something to compare with your data, but a previous 500mb workload took me still on the order of an hour.

**Comment by harmansmithandsons** [comment]
I haven't noticed RAM usage being a source of error prior. I did see a steady increase in memory usage during previous uploads, but that increase happened at a very reasonable rate and I never observed any warning messages about the system running out of memory. I nonetheless still did bump up my VM's RAM allotment (12 --> 32 GiB) just to see if throwing more RAM at it would solve the problem.

I tried the linked script after giving the VM that RAM bump, and even though I noticed some slight inconsistency in upload time (just a couple milliseconds to a few minutes)  for the 500 MiB file, it is nonetheless greatly improved. I also noticed that the RAM usage spiked from ~11% at idle to 30% when uploading, before decreasing back down to the 11% neighborhood.

I also tried to upload this 500 MiB file through the upload page. The upload took ~17 minutes, which is absolutely an improvement, but still appears to do some orders of magnitude off from the numbers you're getting. In contrast to the REST endpoint, I noticed here that the memory usage was near constant; it never exceeded the range of 11.0%-12.9%. 

Given that the main discrepancy is in RAM usage between the two methods of upload, it suggests that there's something specific with the web interface that's causing the bottleneck. Could some component of the web service, something in uWSGI or Flask be doing load balancing/bottleneck prevention and slowing down an upload?

**Comment by jstucke** [comment]
> Could some component of the web service, something in uWSGI or Flask be doing load balancing/bottleneck prevention and slowing down an upload?

I'm still not sure what could cause this. Also I'm sadly unable to really help you in debugging this as long as I can't reproduce this locally. There were some problems previously with uploading large files but after migrating from Flask/Werkzeug 1.x to 2.x they were gone.

**Comment by harmansmithandsons** [comment]
Nevertheless, thank you for the help you were able to provide! RAM usage seems to be a thread to pull on, so I'll likely continue digging in that direction.

**Comment by jstucke** [comment]
If RAM usage is problematic during analysis, you can try to reduce the number of worker processes of the analysis plugins (`processes` in `backend.plugin-defaults` or `backend.plugin`) and unpacking (`processes` in `backend.unpacking`) in `src/config/fact-core-config.toml`.

**Comment by jstucke** [comment]
I just noticed that you also wrote on Gitter and I didn't notice -- sorry for that!

> I also saw that dropzone was previously implemented in [this old commit](https://github.com/fkie-cad/FACT_core/commit/c260a8019c111840dddd051e6a87ba637a584dc9#diff-b09e51feda64d207caeb4733eabd00727d483aa9665cc8a7e07de4f255e6cbb9). I was looking at adding dropzone to my own instance, so I'm curious to know why it was eventually removed, any notable side effects etc.

This was originally intended to fix the upload problems which occurred when uploading large files from the web GUI. As I already mentioned, these problems seemed to disappear when we switched from Flask/Werkzeug 1.x to 2.x, so we did not pursue this further. Maybe it could help with your problems (but there were a lot of changes since then, so it could be easier to reimplement it than to get the branch to work again)
