### ISSUE TITLE
process stop 20hours

### ISSUE THREAD

**Issue by chenjianquan7** [fkie-cad/FACT_core#1149]
### The FACT version you are using

4.1

### Your question

![image](https://github.com/fkie-cad/FACT_core/assets/26828709/0f08d191-6601-4018-a6c7-1ea903f0807c)
 all process stop, why?
it happend sometimes

**Comment by chenjianquan7** [comment]
![image](https://github.com/fkie-cad/FACT_core/assets/26828709/eaae2461-338f-4011-8833-14b7d8db477c)

**Comment by chenjianquan7** [comment]
![image](https://github.com/fkie-cad/FACT_core/assets/26828709/3edb96bb-749f-4dc9-9b1d-daf88d6adcaf)
![image](https://github.com/fkie-cad/FACT_core/assets/26828709/bf2237a4-66e5-4c8e-b5e3-75077c789c90)
![Uploading image.png…]()

**Comment by jstucke** [comment]
Hi, from what I can tell from the logs it seems like the file you are trying to upload as firmware is already in the database as unpacked file from another firmware (this is currently not possible and may cause errors). Could this be the case?

**Comment by jstucke** [comment]
What is more, the file will never leave "currently analyzed firmware" because this file "got lost" during scheduling: All unpacking and analysis tasks should actually be completed but it will not get updated because of the exception. You need to restart FACT to get rid of the entry.
