### ISSUE TITLE
How to initialize new analysis plugin process on existing firmware to all included files?

### ISSUE THREAD

**Issue by paulrichardo** [fkie-cad/FACT_core#1165]
### The FACT version you are using

6cb9354d6ea5160bc56374485db42608ac1b4424

### Your question

Hello,
We have some firmwares uploaded and analyzed.
Wrote some basic plugin that should show us some info, which works fine on singular file from a firmware.
Didn't seem to find a way to initialize this plugin process on existing firmware to all included files.

So, we have 2 questions?
1. How to do it through the Interface?
2. How to do it through REST API?

**Comment by jstucke** [comment]
Hi, I'm not sure if I understand exactly what you mean. Do you want to run your plugin on all files of a firmware that is already in FACT? If so, you can use the "update" button on the analysis page (only visible when you look at the "root" file of the firmware):
![image](https://github.com/fkie-cad/FACT_core/assets/9843800/e5526935-8e2c-4cd5-ad23-d365736e7121)

You can also do this using the REST firmware PUT endpoint using the "update" parameter (see [here](https://github.com/fkie-cad/FACT_core/wiki/Rest-API#put) under "Firmware analysis update")

**Comment by paulrichardo** [comment]
Thank you.
