### ISSUE TITLE
CVE Lookup database updates

### ISSUE THREAD

**Issue by paulrichardo** [fkie-cad/FACT_core#1174]
### The FACT version you are using

6cb9354d6ea5160bc56374485db42608ac1b4424

### Your question

Hello,
I understand that the CVE lookup plugin uses a database with CVEs:
DB_PATH = str(Path(__file__).parent / '../internal/database/cve_cpe.db')
Does the file gets updates? Where from and how often if so?

**Comment by jstucke** [comment]
Hi, this database does not get automatic updates. You can manually update the database by rerunning `src/plugins/analysis/cve_lookup/install.py`.

**Comment by paulrichardo** [comment]
Thank you.
