### ISSUE TITLE
Advanced serach cannot intersect multiple analysis

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#1186]
This does not produce any results, despite there being thousands of files that match this query.
Note that it works if we leave out the query for the `file_type` plugin.
Also these kinds of queries should be documented.
```
{
    "processed_analysis.software_components.OpenSSL": {
        "$exists": "true"
    },
    "processed_analysis.software_components.OpenSSL.meta.version": {
        "$exists": "true"
    },
    "processed_analysis.file_type.mime": "application/x-executable"
}
```

**Comment by jstucke** [comment]
I will close this, since the Advanced Search is planned to be replaced by the GraphQL search (which supports queries like that)
