### ISSUE TITLE
Use maintained fork of binwalk

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#1209]
See https://github.com/ReFirmLabs/binwalk/issues/671 for context.

**Comment by jstucke** [comment]
It seems the fork https://github.com/OSPG/binwalk is already more active than the official repo has been for the last years. Maybe we can simply switch to the fork and use the latest version?

**Comment by ElDavoo** [comment]
for the record, I made the switch in
https://github.com/ElDavoo/fact_extractor/commit/ff81c5a31ab5e6c53652f3f0883abab3a2947980  
Everything seems to work fine

**Comment by ElDavoo** [comment]
And now i also did it https://github.com/ElDavoo/FACT_core/commit/ebd794a096dbb671ec68f7dec54fb83035d21221
