### ISSUE TITLE
No intercom backend binding for "delete file"

### ISSUE THREAD

**Issue by jstucke** [fkie-cad/FACT_core#132]
The intercom backend binding for "delete file" exists but doesn't get started. Therefore, the delete file jobs that are sent over the intercom are not executed.

There might be old delete jobs in the database. Moreover, these old jobs might collide with new analyses: Files that should previously have been deleted were again inserted into the database and the old delete jobs might delete them erroneously. Therefore, a safety check should be implemented to secure that the files that are to be deleted aren't used by existing firmware entries.

**Comment by weidenba** [comment]
solved in #143
