### ISSUE TITLE
Live storage of analysis results leads to possible bug in compare

### ISSUE THREAD

**Issue by dorpvom** [fkie-cad/FACT_core#140]
In short:
The **file coverage** compare plugin has the **file type** analysis plugin as dependency. When objects are stored in the database before **file type** is finished, the compare plugin can run into an error.

What can be done:
It has to be evaluated, what the reaction to such a missing dependency is.
If this is an unwanted szenario - because analysis should always finish before compare - we can error-log this case.
We could also catch the ensuing exception and ignore the affected objects.
The most complex way would be to add something like analysis dependencies to compare plugins. But this would likely involve besides some changes to the scheduling a re-write of nearly all plugins.

**Comment by dorpvom** [comment]
The issue was fixed for now in #141.
The issue should be re-evaluated to decide if a more general solution should be applied

**Comment by weidenba** [comment]
this is an extreme edge case that wont be fixed
