### ISSUE TITLE
Using binary search via API

### ISSUE THREAD

**Issue by IoT-junkrat** [fkie-cad/FACT_core#146]
It would be very nice to use the binary search function via the API.
The return would then be the matching UIDs of the firmware images.

**Comment by weidenba** [comment]
IoT-Junkrat,
this is a great idea and we are going to implement it. However it is holliday season in Germany and this will take some time ;-)

**Comment by IoT-junkrat** [comment]
Thank you very much!
Einen schönen Urlaub :)

**Comment by dorpvom** [comment]
This is currently reviewed in pull request #152

**Comment by dorpvom** [comment]
Please close if changes from #152 are sufficient.

**Comment by jstucke** [comment]
[link to documentation of the new API](https://github.com/fkie-cad/FACT_core/wiki/rest-documentation#restbinary_searchsearch_id)

**Comment by IoT-junkrat** [comment]
Very nice! Thank you for implementing this.
