### ISSUE TITLE
Long statistic entries are often not displayed correctly

### ISSUE THREAD

**Issue by dorpvom** [fkie-cad/FACT_core#181]
When there are longer items on the legend, the names are cut since no line breaks or another fix are configured and the float in which the chart is display has a fixed - if dynamic - width.
Fixing this would allow a proper display of all statistics even on smaller screens.

![stripped_entries](https://user-images.githubusercontent.com/17253091/48469245-97cfa280-e7ee-11e8-9fc0-32663663313f.png)

**Comment by v0idpwn** [comment]
I will take a look

**Comment by jstucke** [comment]
should be fixed with #247
