### ISSUE TITLE
Analysis Bug in same Firmware.

### ISSUE THREAD

**Issue by MasonQAQ** [fkie-cad/FACT_core#190]
The case is : 

>when I upload a Firmware and analysis，the system works well，and the analysis report is complete，all of the analysis components have result，but when I delete the firmware and upload the same Firmware again, the analysis only report several result，some analysis component such as known_vulnerabilities have no result，Why？and when I delete the firmware, restart the system, and upload again, the analysis works well again，Why?

**Comment by weidenba** [comment]
This issue is a duplicate of #156 and is going to be solved soon in #185.
