### ISSUE TITLE
How to detect a firmware analysis completed

### ISSUE THREAD

**Issue by yifiHeaven** [fkie-cad/FACT_core#215]
How to accurately know the end of a firmware analysis

**Comment by weidenba** [comment]
The "System" tab provides a list of the number of files in each plug-in and unpacking queue. If all queues are empty, the analysis should be finished.

**Comment by yifiHeaven** [comment]
When multiple firmwares are analyzed at the same time, how to accurately know that a firmware analysis has been completed

**Comment by weidenba** [comment]
Unfortunately, there is no easy way to do this at the moment.
You could write a REST script, that recursivly checks, if all included files and all the desired analysis are present in the database.
