### ISSUE TITLE
Report generation

### ISSUE THREAD

**Issue by plutec** [fkie-cad/FACT_core#23]
It would be great if exists the posibility to create a report (HTML, for instance) given a firmware with all the information extracted.

**Comment by dorpvom** [comment]
Hi,
we experimented with latex-based PDF reports in the past, but the issue of independent visualization of plugin results as well as the size of the included files tree have shown to be non-trivial. We will still look at this at some point but not likely in the upcoming weeks.

**Comment by dorpvom** [comment]
Update: Someone is looking into pdf-report generation at the moment. I'll update this thread once real progress is made.

**Comment by weidenba** [comment]
The project dorpvom mentioned has a first functional version. The project can be found [here](https://github.com/any333/FACT_analysis_report_pdf_convertor).

**Comment by weidenba** [comment]
There is new [project](https://github.com/fkie-cad/fact_pdf_report) that is going to solve this issue. It will support theming so that you can easly modify the reports to suit your needs.

**Comment by dorpvom** [comment]
See branch [support-beta-pdf-report](https://github.com/fkie-cad/FACT_core/tree/support-beta-pdf-report) for progess

**Comment by dorpvom** [comment]
We now have a button for generating and downloading a basic pdf report. Was merged in #276.
