### ISSUE TITLE
Login Features

### ISSUE THREAD

**Issue by mryu-org** [fkie-cad/FACT_core#238]
Hi, how can I use login to control users?

**Comment by dorpvom** [comment]
Hi,
have a look at our [wiki page on authenticaion](https://github.com/fkie-cad/FACT_core/wiki/Authentication).
In short you have to enable authentication through an option in the `main.cfg` file, create a root user through the `src/manage_users.py` script and then you can use the user management tab of the WebUI (only visible when auth is enabled).

**Comment by mryu-org** [comment]
> Hi,
> have a look at our [wiki page on authenticaion](https://github.com/fkie-cad/FACT_core/wiki/Authentication).
> In short you have to enable authentication through an option in the `main.cfg` file, create a root user through the `src/manage_users.py` script and then you can use the user management tab of the WebUI (only visible when auth is enabled).

dorpvom thanks!!!!
