### ISSUE TITLE
Unpack Throttle Limit seems to be broken

### ISSUE THREAD

**Issue by weidenba** [fkie-cad/FACT_core#262]

**Comment by jstucke** [comment]
this could also be a problem with the `sleep` in `test_throttle` being to short for the new slower CI

**Comment by weidenba** [comment]
It actually happens during real analysis. The Monitor is active since it logs status messages. However throttleing does not work.

**Comment by dorpvom** [comment]
Issue seems to not occur regularly. No easy way to debug this due to heavy use of multiprocessing.
Test cases or repeatable scenarios are needed at this point.

**Comment by jstucke** [comment]
This should hopefully be fixed now
