### ISSUE TITLE
PDF Generator

### ISSUE THREAD

**Issue by ksw9722** [fkie-cad/FACT_core#267]
Hello. Sorry for my stupid english. 

 I want to analysis report about FACT result. 

I'm verified report generation function. (https://github.com/fkie-cad/fact_pdf_report)

But this page didn't have any source code. 

Why isn't there any source code?

**Comment by weidenba** [comment]
Hi ksw9722,

actually the tool is still under development. There is an "init" branch containing the code. However it is still not functional at the moment. I close this issue, because there is  an issue regarding a report generation tool (#23) already.
