### ISSUE TITLE
Search for release date of a binary (stats page) does not work

### ISSUE THREAD

**Issue by IoT-junkrat** [fkie-cad/FACT_core#307]
Hey guys,

when I want to click on the histogram on the statistics page to display for a certain month, which binaries were released, the filter qurery is correctly shown in the URL. Unfortunately, FACT shows all the binaries unfiltered. 
Would be happy if you could fix that.
Thank you!
Cheers

**Comment by dorpvom** [comment]
Hi,
I can confirm this. We'll look into it.

**Comment by jstucke** [comment]
Please confirm if the bug is fixed or if it still occurs.

**Comment by IoT-junkrat** [comment]
Fix confirmed, thank you!
