### ISSUE TITLE
python entropy moudle have been removed, can not install FACT

### ISSUE THREAD

**Issue by aodzip** [fkie-cad/FACT_core#345]
install script contain a pip package called entropy , it will fail to install. it seems have been removed from pip repositories.

**Comment by weidenba** [comment]
Thanks for the note. We will have a look at it asap.

**Comment by dorpvom** [comment]
Confirmed. Original repo is down. There are forks so we'll look on a short term fix, before evaluating alternatives.
Meanwhile you can manually remove the installation from the script and install one of the forks:

`pip3 install git+https://github.com/armbues/python-entropy`

**Comment by weidenba** [comment]
Fix has been merged to master.
