### ISSUE TITLE
Stored XSS when updating analysis details

### ISSUE THREAD

**Issue by lum8rjack** [fkie-cad/FACT_core#375]
The application does not sanitize the user input when updating the details of a firmware. When updating the firmware details, the applications posts the data to the "upload-analysis/[uid]" page. That page then runs the function "_get_meta_from_request()" within the /src/helperFunctions/mongo_task_conversion.py script. I tested the "tags" and "version" fields by adding JavaScript to the updated fields (it looks like other fields are possibly vulnerable too). This data is not sanitized and is stored in the application. Each time a page is requested with this information, the JavaScript is ran. I added some screenshots to help. Using the "escape" function within flask could be a solution to sanitize the input. I tested it against the version field and it worked. Let me know if there are any additional questions.

![1_post](https://user-images.githubusercontent.com/4932619/77856521-6118e300-71bd-11ea-9cff-65b243ef2ced.png)
Adding js to the tags field
![3_injected](https://user-images.githubusercontent.com/4932619/77856528-6b3ae180-71bd-11ea-8d83-9c5c0a819e0d.png)
When browsing to the home page it loads the js
![2_popup](https://user-images.githubusercontent.com/4932619/77856529-6d9d3b80-71bd-11ea-9f92-1209f04ed1d7.png)
js is executed
![4_sourcecode_escape](https://user-images.githubusercontent.com/4932619/77856532-7130c280-71bd-11ea-87a1-788b3cdada8f.png)
Used the escape function to sanitize the input
![5_escaped](https://user-images.githubusercontent.com/4932619/77856537-755ce000-71bd-11ea-9c42-7fa675aa1c68.png)

**Comment by dorpvom** [comment]
Hi,

we actually did not do a great job securing our web application, thus the warning in our *readme*. That said we're happy to improve security wherever possible. Mostly we simply lack the background in web application design.
Would you like to open a Pull Request on that yourself, since you seem to have a solution already?

Best,
Johannes

**Comment by lum8rjack** [comment]
Thanks for the quick response. Yeah I can test the solution to make sure it works and doesn't affect anything else and then open a pull request.

Clint

**Comment by weidenba** [comment]
fix merged
