### ISSUE TITLE
Change Vendor Name in existing Analysis

### ISSUE THREAD

**Issue by dsyman** [fkie-cad/FACT_core#440]
May I change a firmware's Vendor Name after its analysis is terminated?

**Comment by dorpvom** [comment]
Hi,
currently you can only do this by using the _update_ analysis feature. It's one of the buttons on top of the analysis page.
Using that you get the same dialogue as for upload. You have to at least run the unpacking for the firmware again, but you can deselect all analysis plug ins to save time and computing resources.

Safe to say, we viewed this as an edge case feature until now. You can reopen this issue and rename it to something in line of "Support easier option for changing meta information" if you like, then it's on the to do list.

BTW you can also use our [gitter channel](https://gitter.im/FACT_core/community) to ask questions any time.
