### ISSUE TITLE
Import-Export analysys result

### ISSUE THREAD

**Issue by dsyman** [fkie-cad/FACT_core#446]
I need to transfer some analyses results from a FACT machine to another.
Is there anyway to accomplish this task?

**Comment by jstucke** [comment]
You could only transfer the complete database to another machine. At the moment, there is no import functionality for analysis results. 
In theory, you could merge the files and add the data using the MongoDB command line (but that could be very complicated).
We could add this to the REST API but then problems could arise when some files or data is missing (we would need some way to make sure the data is consistent).
