### ISSUE TITLE
Reboot before executing the src/install.py

### ISSUE THREAD

**Issue by weekbin** [fkie-cad/FACT_core#465]
Hi ~
I am confused about the installation process，why is it necessary to reboot before executing the src/install.py ?

**Comment by weekbin** [comment]
Which dependency makes the reboot necessary? Is there a way to bypass the restart ？

**Comment by dorpvom** [comment]
Hi.
It's the docker daemon. That does not start directly upon installation (and also not with systemctl / service start). If you had docker previously, you can just go ahead without reboot. Also, logging out of the session should probably suffice so you don't even necessarily need to restart even on a new setup.

**Comment by weekbin** [comment]
thanks a lot !
