### ISSUE TITLE
Extracted firmware location??

### ISSUE THREAD

**Issue by csenger18** [fkie-cad/FACT_core#490]
Is it possible to download whole folders from file tree? (single files is downloadable)

**Comment by csenger18** [comment]
Where FACT stores extracted firmware files?

**Comment by jstucke** [comment]
> Is it possible to download whole folders from file tree? (single files is downloadable)

You can use the "Download included files as tar.gz" button on the analysis page to download all files in a file system or archive. It is not possible to download all files from a specific folder.

> Where FACT stores extracted firmware files?

By default, the files are stored in `/media/data/fact_fw_data/` with their UID as filename.

**Comment by csenger18** [comment]
thanks
