### ISSUE TITLE
Creation of signatures failed

### ISSUE THREAD

**Issue by terorr** [fkie-cad/FACT_core#502]
./compile_yara_signatures.py 
Create signature directory /home/hjk/FACT_core/src/analysis/signatures
Compile signatures in /home/hjk/FACT_core/src/plugins/analysis/software_components/signatures
Compile signatures in /home/hjk/FACT_core/src/plugins/analysis/crypto_hints/signatures
[ERRROR] Creation of /home/hjk/FACT_core/src/analysis/signatures failed !!
Compile signatures in /home/hjk/FACT_core/src/plugins/analysis/crypto_material/signatures
Compile signatures in /home/hjk/FACT_core/src/plugins/analysis/known_vulnerabilities/signatures

**Comment by jstucke** [comment]
Hi, I could not reproduce the error. Do you have a different Yara version installed than 3.7.1? Did you change any of the signatures?
It seems that `src/plugins/analysis/crypto_hints/signatures` caused the error. It would be interesting to see the actual error message. Could you please post the result of 
```yarac -d test_flag=false -w src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar  /tmp/signature.yc```?

**Comment by terorr** [comment]
$ yarac -d test_flag=false -w src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar /tmp/signature.yc
src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar(6): error: syntax error, unexpected _LT_
src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar(21): error: unterminated regular expression





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fkie-cad/FACT_core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 下午3:14
收件人:&nbsp;"fkie-cad/FACT_core"<FACT_core@noreply.github.com&gt;;
抄送:&nbsp;"然后呢O_o"<1980258444@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fkie-cad/FACT_core] Creation of signatures failed (#502)





 
Hi, I could not reproduce the error. Do you have a different Yara version installed than 3.7.1? Did you change any of the signatures?
 It seems that src/plugins/analysis/crypto_hints/signatures caused the error. It would be interesting to see the actual error message. Could you please post the result of
 yarac -d test_flag=false -w src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar  /tmp/signature.yc?

**Comment by jstucke** [comment]
> src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar(21): error: unterminated regular expression

As far as I can tell, there shouldn't even be a regular expression in that line. The file is installed from `https://github.com/Yara-Rules/rules/blob/master/crypto/crypto_signatures.yar`. You could try running `src/plugins/analysis/crypto_hints/install.sh` again. 
Did you perhaps change the file? Can you post the Yara rule from the file which is causing the error message?

**Comment by terorr** [comment]
OK，thank you！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fkie-cad/FACT_core"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 下午4:01
收件人:&nbsp;"fkie-cad/FACT_core"<FACT_core@noreply.github.com&gt;;
抄送:&nbsp;"然后呢O_o"<1980258444@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fkie-cad/FACT_core] Creation of signatures failed (#502)





  
src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar(21): error: unterminated regular expression
  
As far as I can tell, there shouldn't even be a regular expression in that line. The file is installed from https://github.com/Yara-Rules/rules/blob/master/crypto/crypto_signatures.yar. You could try running src/plugins/analysis/crypto_hints/install.sh again.
 Did you perhaps change the file? Can you post the Yara rule from the file which is causing the error message?

**Comment by dorpvom** [comment]
Sound like issue is fixed? Re-open otherwise
