### ISSUE TITLE
When I generated the PDF report, there was no detailed report, just a list of data;

### ISSUE THREAD

**Issue by 13724460607** [fkie-cad/FACT_core#590]
I think there is a detailed description on the PDF report. How should I operate it?Is it my program?
![image](https://user-images.githubusercontent.com/52743072/120980395-293a0200-c7a9-11eb-99df-743fe3b9bd9e.png)

**Comment by jstucke** [comment]
I'm not sure if I understand your question correctly. This is the way the PDF report is supposed to look. It contains a brief summary of the most important results that were found during the analysis and nothing more.

**Comment by 13724460607** [comment]
Yes, if you want to see the full result, can you only access it from a Web interface or REST endpoint?

**Comment by jstucke** [comment]
Yes, the PDF report does not contain all results. It is intended as a short summary.

**Comment by 13724460607** [comment]
Thank you. I have received your patient reply
