### ISSUE TITLE
After scanning three files, the newly added file has no scan result

### ISSUE THREAD

**Issue by 13724460607** [fkie-cad/FACT_core#602]
First of all, I added three firmware packages in increments, and scanned the results, and then uploaded the fourth firmware package, submitted the display "Upload Successful", but kept refreshing "The analysis will be available here once it is finished" "No results are displayed. Finally, I went to see "info-system" and kept seeing this program running. I waited for a few days and no results were displayed.

my question is:
1.How to delete the previously uploaded firmware package
2.How to solve the problem that the above description does not display results.

Thank you FACT team

**Comment by jstucke** [comment]
If there was an error, it should be logged to the CLI where the FACT backend or frontend runs (depending on where it happened and whether you started the components individually or together). Errors are also logged to the file which is configured in the main config (`/tmp/fact_main.log` by default). 

If you see "Upload Successful" but cannot access the results page, then no results were stored in the database. It could mean that the backend was not running correctly or there was an error during unpacking. You could simply try to restart FACT and try uploading the firmware again. Previously uploaded files and stored analysis data will be overwritten.

The actual files are stored to the directory in the backend defined in `main.cfg` (by default `/media/data/fact_fw_data/`). The file name is "\<MD5 hash\>_\<file size in bytes\>" so you could compute the MD5 hash of your firmware and delete it manually if necessary.
