### ISSUE TITLE
How do I enter the database to delete historical data?

### ISSUE THREAD

**Issue by 13724460607** [fkie-cad/FACT_core#614]
I have uploaded a lot of data before, now the amount of data is a little large, I want to delete the previous historical data;  
1.How do I connect to the database?
2.How do I delete data?

**Comment by jstucke** [comment]
When you are on the analysis page of a firmware, there is a small button with a garbage bin icon at the top. This button can be used to delete the firmware, all its included files and all analysis results. 
If you want to directly delete documents from the database you should refer to the [MongoDB documentation](https://docs.mongodb.com/manual/tutorial/remove-documents/).

**Comment by 13724460607** [comment]
thank you
