### ISSUE TITLE
Incompatible dependencies: flask-API

### ISSUE THREAD

**Issue by mistressofjellyfish** [fkie-cad/FACT_core#624]
`requirements_frontend.txt` specifies flask==1.1.2, but no Version for `flask-api` (https://github.com/flask-api/flask-api).

`flask-api` recently released version 3.0, which requires `flask` >= 2.0.

Solution: flask-api should be fixed to a 2.x version compatible with flask 1.1.2.

**Comment by mistressofjellyfish** [comment]
Addendum: the correct version for flask-api should be 2.0 according [to the history on pypi](https://pypi.org/project/Flask-API/#history).

**Comment by jstucke** [comment]
It seems like we don't actually use flask-api anywhere. If the CI builds are successful it will get removed in #627
