### ISSUE TITLE
Suggestion: replace jshint with eslint

### ISSUE THREAD

**Issue by mistressofjellyfish** [fkie-cad/FACT_core#639]
The linter plugin uses jshint as a javascript linter. While there is nothing inherently wrong with that, eslint is the default for many modern web projects. For example, JSHint cannot parse reacts .jsx files, and most modern web frameworks like react, vue or angular are only really well supported with rules for eslint.

So, I think the quality of the linter output could be improved by switching linter.

**Comment by jstucke** [comment]
This is a good suggestion and we will probably switch to eslint as soon as we find time to make the changes
