### ISSUE TITLE
What can I do if an error is displayed when I execute./install.py

### ISSUE THREAD

**Issue by barkosHuang** [fkie-cad/FACT_core#657]
![image](https://user-images.githubusercontent.com/52743072/137064982-066a38aa-ad55-40b0-937e-012d023033e2.png)

**Comment by barkosHuang** [comment]
thanks；
I now go to the path (SRC /plugins/analysis/cve_lookup/internal/) to update.  
ERROR:root:CVE tables do not exist! Did you mean import CVE?
What should I do next?

**Comment by jstucke** [comment]
Could you try to delete the database `src/plugins/analysis/cve_lookup/internal/cve_cpe.db` (if it exists) and then run `python3 setup_repository.py` (without the `--update` parameter)?

**Comment by jstucke** [comment]
If `python3 setup_repository.py` completed without errors, you can try to run `src/install.py` again, yes.

**Comment by barkosHuang** [comment]
thank you very much
My server is ubuntu
But I don't understand why it keeps stuck in the install static jstree content command.
