### ISSUE TITLE
HOW to use FACT PDF report ?

### ISSUE THREAD

**Issue by Key20** [fkie-cad/FACT_core#672]
FACT report generate Few results，must add FACT PDF report function(https://github.com/fkie-cad/fact_pdf_report)? AND how to use FACT PDF report

**Comment by jstucke** [comment]
As I said before, the PDF report as it is only summarizes the most important results. If you want more, you would have to edit the code in https://github.com/fkie-cad/fact_pdf_report and rebuild the container or create your own PDF report from scratch.

**Comment by jstucke** [comment]
You can look at the template: https://github.com/fkie-cad/fact_pdf_report/blob/master/pdf_generator/templates/default/main.tex
It is intended to be brief and only list the most important findings

**Comment by Key20** [comment]
OK，thanks very much
