### ISSUE TITLE
What is the function of 8000 port?

### ISSUE THREAD

**Issue by barkosHuang** [fkie-cad/FACT_core#676]
What is the function of 8000 port?

I installed mobsf on my server. It uses 8000 port. I saw in fact that 8000 port also exists here. Can I directly modify 8000 port to other ports in the fact program?
![image](https://user-images.githubusercontent.com/52743072/139773531-96fac64d-b8b7-4625-bbb2-b1266cb269c6.png)

**Comment by jstucke** [comment]
It is used for radare (the "View in radare" button on the analysis results page). It should be safe to change it, but you need to change the port in `_get_radare_endpoint()` in `src/web_interface/components/io_routes.py` (and possibly other locations) if you still want to use that button.

Also you could simply turn off the radare containers by commenting out the `docker-compose` lines in `src/start_fact_frontend.py` if you don't need them.

**Comment by rhelmke** [comment]
Hey, we are going to close this issue for the time being. In case there are any followup questions regarding this matter, feel free to re-open it.

Cheers.
