### ISSUE TITLE
Feature Request: Add a "Force Update" option to the "Updata Analysis" operation

### ISSUE THREAD

**Issue by frakman1** [fkie-cad/FACT_core#678]
When binwalk fails for any reason during a firmware analysis run, but leaves some erroneous or incomplete data in the results, there is no option to update the analysis on the firmware and only perform a binwalk for all files. 

The current options are:
1- Perform binwalk manually on each file via`Run additional Analysis` -> `Force analysis update`. 
2- Redo entire firmware analysis via Admin-> `redo analysis`. This can be very time consuming for large firmware

The ideal solution would be to do a `Analysis` -> `Update Analysis` and check the `binwalk` option and have it update the binwalk results for all files and leave eveyrthing else untouched.

This relates to the discussion [here](https://github.com/fkie-cad/FACT_docker/issues/5#issuecomment-957160758):

**Comment by jstucke** [comment]
#680 should add this feature
