### ISSUE TITLE
not handling optional field 'tags' properly through rest api

### ISSUE THREAD

**Issue by wideglide** [fkie-cad/FACT_core#684]
'tags' is an optional attribute of the firmware model, but if the `tags` attribute is not provided, the backend crashes as there's no default value for `tags`.

The frontend bails here because `tag_string` is None.
https://github.com/fkie-cad/FACT_core/blob/0ab195bfe23c50f2d0a88ad75085d67a467d6f88/src/helperFunctions/mongo_task_conversion.py#L97

This happens through the API `rest/firmware` endpoint.

**Comment by jstucke** [comment]
Thank you for reporting this bug. #686 should fix it
