### ISSUE TITLE
Know vulnerabilities is None

### ISSUE THREAD

**Issue by KongLynn** [fkie-cad/FACT_core#695]
I have scanned multiple firmwares but none of their known vulnerabilities. Can you tell me the specific scan contents of the known vulnerabilities module？ Thank you very much.

**Comment by Enkelmann** [comment]
I only meant that the cwe_checker repository is the wrong repository for the issue and that you should ask this question in the FACT_core repository.

Edit: Oh, and I see you did just that yesterday. Then I can close this issue as a duplicate.

**Comment by KongLynn** [comment]
Oh，ok，thanks～
