### ISSUE TITLE
hash type not supported

### ISSUE THREAD

**Issue by frakman1** [fkie-cad/FACT_core#705]
If my understanding is correct, then the format for the `/etc/passwd` entry is:
`$id$salt$encrypted`
where `id` is the encryption method, right?

So how come it was able to accept the hash type for the second entry and decrypt it, but not the first one?

![image](https://user-images.githubusercontent.com/5826484/144095585-6b59047c-b655-4a19-86b9-a24efc138aff.png)

**Comment by jstucke** [comment]
"hash type is not supported" is more like a general error message when cracking the password failed. It sure looks like a normal MD5 entry. I can't tell what exactly went wrong, though. You could try it manually by copying the hash into a text file and running john (at least this could tell us what went wrong):

```shell
src/plugins/analysis/users_and_passwords/bin/john hash.txt
```
