### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by frakman1** [fkie-cad/FACT_core#710]
The documentation page's screenshot shows a user management feature.
I was unable to find this page in my docker based installation. Is it implemented?

![image](https://user-images.githubusercontent.com/5826484/144275953-d65c327e-1c5a-44c9-a2e9-404abaf69a45.png)

https://fkie-cad.github.io/FACT_core/_images/10_user_management.png

**Comment by rhelmke** [comment]
Hey,

check out [this](https://github.com/fkie-cad/FACT_core/wiki/Authentication) article:

For this to work you must globally enable authentication, which you can do by setting `authentication=true` in `src/config/main.cfg`. Then create your admin user by running the helper CLI in `src/manage_users.py`. Remember to assign the `superuser` role to your created user via the `add_role_to_user` command after creation. Now you can start FACT and will be greeted with a login prompt. Once logged in, you will see the `Manage Users` item under the `Admin` tab.

**Comment by rhelmke** [comment]
Hello,

I hope I was able to help you here. Do not hesitate to reopen this ticket if the problem still persists.
