### ISSUE TITLE
I may have found the problem about ClamAV in OMS

### ISSUE THREAD

**Issue by cen6667** [fkie-cad/FACT_core#747]
“common_analysis_oms/common_analysis_oms/plugins/ClamAV.json”
There may be an error in the terminal command.

# clamdscan './data/eicar'
![image](https://user-images.githubusercontent.com/67215703/157832574-feaa45d2-f592-48ab-83ce-e953d82a9870.png)

but
# clamscan './data/eicar'
![image](https://user-images.githubusercontent.com/67215703/157832255-a81ff90e-71e4-4201-94a9-b9322fddaeed.png)

**Comment by jstucke** [comment]
Hi, the message "Could not connect to clamd" usually means that the clamav-daemon service is not running. `clamdscan` uses the clamav daemon service (which should be running in the background) for scanning, which is much faster than `clamscan`. You should be able to check the status with `service clamav-daemon status`. If it is not running, it should be possible to start it with `sudo service clamav-daemon start` (or restart it with `sudo service clamav-daemon restart` if it crashed). 

If this doesn't work, clamav may not be installed correctly. You can try to reinstall it with `python3 src/plugins/analysis/oms/install.py`.

**Comment by jstucke** [comment]
Since the plugin was removed in #732 I will close the issue.
