### ISSUE TITLE
Presets for analysis systems

### ISSUE THREAD

**Issue by dorpvom** [fkie-cad/FACT_core#75]
As of now the config file lists default plugins that are preselect on the upload page.

This could be enhanced to support custom presets. The upload page could then contain a dropdown menu to switch between presets.

Presets could be defined in config just as the default plugins are now.

Preset ideas:

- Full (duh)
- Fast (none selected)
- UNIX Firmware (init systems, passwords, software components ..)
- Component (binwalk, printable strings, ip finder)
- ..

**Comment by weidenba** [comment]
Feature is implemented
