### ISSUE TITLE
Not working anymore ? 

### ISSUE THREAD

**Issue by iDustbin** [fkie-cad/FACT_core#750]
Hi, i tried to upload firmware: 
OS: Ubuntu 18.04: installation seems to be fine, i see in uwsgi log the following message: 

Queue Length (Analysis/Unpack): 0 / 0

Upload and Unpacking seems not to be working ? any idea ?

**Comment by jstucke** [comment]
It sounds like the upload was not successful. Did you see any errors / stack traces appear in the logs? If everything seems to work normally you could also try uploading the file via the REST endpoint: https://github.com/fkie-cad/FACT_core/wiki/Rest-API#restfirmwareuid
There was an issue with firefox and the upload of very large files timing out. How large is the file you are trying to submit?
