### ISSUE TITLE
Upload firmware takes too long

### ISSUE THREAD

**Issue by anesic-c4** [fkie-cad/FACT_core#762]
I tried to upload .bin, .tar and .zip firmwares. 
It takes couple of hours where in GUI states Upload Firmware and Pacman gif, while in Terminal I have this **INFO**: 
[Unpacking][INFO]:  Queue Length (Analysis/Unpack):  0/0

**Comment by jstucke** [comment]
This should be fixed with #760 so it should hopefully be enough to do a `git pull` in the FACT directory and restart FACT.

**Comment by anesic-c4** [comment]
Thanks, I uploaded successfully now. 
Kind regards
