### ISSUE TITLE
I got an error when i try to run a `software_components` plugin 

### ISSUE THREAD

**Issue by hezygo** [fkie-cad/FACT_core#765]
### here my main code
![image](https://user-images.githubusercontent.com/58553737/162346484-55581227-3d86-4743-9074-b314ccdfdd6e.png)
### and here my log
![image](https://user-images.githubusercontent.com/58553737/162345882-7a9dab44-72dc-482f-ba4a-85db359e6de0.png)
**_is  the error caused by my input args?_**

#### supplement
![image](https://user-images.githubusercontent.com/58553737/162357288-db64d29f-c8ca-4513-9c18-1c588b664a4b.png)
![image](https://user-images.githubusercontent.com/58553737/162358025-4a6858e8-513e-44de-a5ac-3d1bb80f95d9.png)

##### should i alter the yara file？

**Comment by rhelmke** [comment]
Hello @hezygo.

It seems like you are trying to extract selected code components of FACT and interface with them using your own standalone script. While that is totally fine, we kindly remind you that FACT is a tightly integrated application that depends on many different components. It is very likely that something will break when you interface with single components. 

We understand that FACT is far from complete in its use case and, thus, provide well-defined APIs for interaction with other tools to mitigate possible problems. For these, we gladly provide support and are open for new suggestions and pull requests. However, what you are trying to achieve is beyond the scope of our project.

Thus, I'm closing this issue.

**Comment by jstucke** [comment]
Some pointers:
- I'm not really sure what you are trying to accomplish but the plugins are not intended to be used outside of FACT
- all the yara rules of the software_components plugin are compiled into `src/analysis/signatures/software_components.yc` by the script `src/compile_yara_signatures.py`
- The rule "no_text_file" uses yara's magic module so you need to compile yara with magic support (see https://yara.readthedocs.io/en/v4.2.0/gettingstarted.html#compiling-yara)
