### ISSUE TITLE
User defined tags color can't be set

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#812]
The color of user defined tags always defaults to gray.
In the code there is support for setting a custom color, but it can't be set through the user interface.
We could either support setting custom colors or adapt the code to make clear that we don't support multiple colors.

Relevant function: `Firmware.set_tag`

**Comment by jstucke** [comment]
I don't think the feature is necessary: all user tags have the same color and the other tag colors are used by analysis tags. Therefore, the custom color support could be removed IMHO
