### ISSUE TITLE
Run the update_statistic program.

### ISSUE THREAD

**Issue by harry1080** [fkie-cad/FACT_core#853]
How to update this data

Run the update_statistic program.
![image](https://user-images.githubusercontent.com/19358692/189589722-a55a3a0c-a899-41dc-8e3b-f62e0e991fd0.png)

**Comment by rhelmke** [comment]
Hey buddy,

please run the mentioned python script in your local FACT folder under [src/update_statistic.py](https://github.com/fkie-cad/FACT_core/blob/master/src/update_statistic.py) while FACT is running.

**Comment by harry1080** [comment]
hello buddy,
I have executed this program as you said, but the data is still not displayed data. Why? 

![image](https://user-images.githubusercontent.com/19358692/189624359-73df11c6-731e-4b1d-87dd-103fa554e2bc.png)

**Comment by harry1080** [comment]
Hello, brother

After reading the articles written by other leaders, I found that there should be a route in this position, as shown in the following figure:

![image](https://user-images.githubusercontent.com/19358692/189789141-501c8f2c-97e9-46c3-a488-84a345f493d6.png)

But the system installed on my side does not have this option. Is this not the default, or is there a problem with my installation,

![image](https://user-images.githubusercontent.com/19358692/189789491-8d5c8b37-a00f-4205-84fe-fe77181842f0.png)

**Comment by rhelmke** [comment]
Just must analyze firmware before getting statistics about them.

The meta data shown in the first image is not the default. You are supposed to organize your firmware samples by yourself -- meaning you need to select `new entry` and type in your device class.

**Comment by harry1080** [comment]
Hey buddy,
Received, thank you for your advice, solved this problem, you can close this issues

**Comment by rhelmke** [comment]
Cheers!
