### ISSUE TITLE
faced some problem with database

### ISSUE THREAD

**Issue by Oddluo** [fkie-cad/FACT_core#859]
hey,I encountered this error after closing FACT and restarting, it seems like the problem with the database, Have you ever met？What should i do ?  Do I need to reinstall？
![图片](https://user-images.githubusercontent.com/67694128/191639451-2a594f1a-8ada-4ae7-861f-7e175cf4006c.png)

**Comment by dorpvom** [comment]
Hi Oddlou,
this is quite a unique error and I've only seen similar errors when the RAM runs full (and objects might not be stored correctly anymore). I would cook up a patch to add some debug information if you can reproduce the error. Have you tried reproducing it yet?

**Comment by Oddluo** [comment]
> 

hello，I fixed it by restarting it several times, and i don't know why ,maybe just a bug？ I can't reproduce it and i will closed this issue , thx.
