### ISSUE TITLE
ERROR: Could not connect to clamd on LocalSocket /var/run/clamav/clamd.ctl: No such file or directory

### ISSUE THREAD

**Issue by emorasoul** [fkie-cad/FACT_core#860]
when i analyzing a firmware，a error report frequently！I don't know what happy？
![image](https://user-images.githubusercontent.com/7411861/191928929-78d3b6df-69e1-4dd1-a993-3c02a69aa789.png)

**Comment by dorpvom** [comment]
Hi emorasoul,
I can't say why but it's coming from the malware detection plugin. As the plugin is marked for deprecation, we'll probably don't invest a lot into investigation but we'll look if we can make sense of the message.

**Comment by jstucke** [comment]
It seems other people had similar problems with ClamAV and were able to resolve them: https://askubuntu.com/questions/1170774/clamav-clamd-ctl-file-is-not-getting-created-on-ubuntu

**Comment by jstucke** [comment]
Incidentally "resolved" by removal of the malware scanner plugin #732
