### ISSUE TITLE
Change sphinx theme

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#868]
On my ubuntu 22.04 install building the docs results in the following error:
```
Running Sphinx v4.3.2

Warning, treated as error:
sphinx_rtd_theme (< 0.3.0) found. It will not be available since Sphinx-6.0
make: *** [Makefile:20: html] Error 2
```

So we should probably change the theme.
Also: Did we document somewhere what dependencys building the docs has?
`apt install sphinx-common` and `pip install sphinx-rtd-theme` seem to be it.

**Comment by jstucke** [comment]
> Also: Did we document somewhere what dependencys building the docs has?

Did you try to look at the readme (`/docsrc/README.md`)? It should build fine if you follow the instructions :sweat_smile: 
Despite that, we could probably update the versions in the `doc_dependencies.txt`.

**Comment by maringuu** [comment]
> Did you try to look at the readme (/docsrc/README.md)? 

Whoops. No I missed that. I'd propose to add a link to it in the README.

**Comment by jstucke** [comment]
> > Did you try to look at the readme (/docsrc/README.md)?
> 
> Whoops. No I missed that. I'd propose to add a link to it in the README.

Since there is already a link in the README.md to https://fkie-cad.github.io/FACT_core/ and most users probably don't want to build the docs locally, I don't think this is really necessary. Since the underlying problem is fixed, I will close the issue.
