### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by keeplearning-rgb** [fkie-cad/FACT_core#874]
Progress bar keeps stuck at 10/3983. CPU usage is also 72% throughout.
How can it be confirmed that progress is completed OR what's the reason that progress bar is stuck 

Please provide some solution
![image (17)](https://user-images.githubusercontent.com/72157228/195569629-19be3986-87e6-4b90-af4c-3c607efd126b.png)

**Comment by jstucke** [comment]
This should hopefully be resolved by now. If not, feel free to reopen the issue.
