### ISSUE TITLE
analysis detail info can not display，i don't known what‘s the matter？

### ISSUE THREAD

**Issue by emorasoul** [fkie-cad/FACT_core#875]
![image](https://user-images.githubusercontent.com/7411861/195581410-886b0652-8b3c-4e96-a532-b685fb02d253.png)
![image](https://user-images.githubusercontent.com/7411861/195581519-7ad8f2be-1d98-4be4-9ecd-603ed76dccfa.png)

**Comment by emorasoul** [comment]
summary is ok

**Comment by jstucke** [comment]
The JavaScript error only means that the loading animation for the summary didn't load (I don't know why, though)

**Comment by emorasoul** [comment]
OK，thanks！

**Comment by dorpvom** [comment]
I guess we can close this? @emorasoul Re-open otherwise

**Comment by emorasoul** [comment]
sorry，I forgot to close.



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 14, 2022 19:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fkie-cad/FACT_core] analysis detail info can not display，i don't known what‘s the matter？ (Issue #875)




 
I guess we can close this? @emorasoul Re-open otherwise
