### ISSUE TITLE
ERROR:root:CVE tables do not exist! Did you mean import CVE?

### ISSUE THREAD

**Issue by star-star-87** [fkie-cad/FACT_core#918]
anyon ever met this ? can help?

**Comment by jstucke** [comment]
This seems to be a problem with the "cve_lookup" plugin's installation. Could you try to remove the database `src/plugins/analysis/cve_lookup/cve_cpe.db` and rerun the installation with

```bash
python3 src/plugins/analysis/cve_lookup/install.py
```

**Comment by maringuu** [comment]
Closed by removing the database altogether in https://github.com/fkie-cad/FACT_core/pull/1083
