### ISSUE TITLE
Don't kill the whole processgrop on CTRL-C

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#938]
Just sending SIGKILL to the whole processgroup after shutting down was (kind of) successful is confusing.
As the terminal will always show `killed` and the exit code will not be zero.

See also https://github.com/fkie-cad/FACT_core/pull/809#issuecomment-1268554211

**Comment by jstucke** [comment]
We had issues with subprocesses continuing to run as "zombie processes" after shutdown when exceptions occurred at certain places in the code. This can lead to all kinds of interesting problems if a "shadow" frontend or backend is still running in the background. Killing the process group was the only halfway reliable way to fix this but maybe you can think of a better way.

**Comment by jstucke** [comment]
Should be resolved in https://github.com/fkie-cad/FACT_core/pull/953
