### ISSUE TITLE
code: Don't call processes threads

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_core#950]
We use pythons `multiprocessing` all the time but they are called thread which is a different thing.
I'm not sure if it is worth the time to fix this but I think we should definitely not refer to the processes as threads in the `main.cfg` because this might confuse users.

Probably closes https://github.com/fkie-cad/FACT_core/issues/810

**Comment by jstucke** [comment]
I agree. I would suggest to name it "worker count" or "workers" instead.
