### ISSUE TITLE
fix password bug with passlib/flask-security

### ISSUE THREAD

**Issue by jstucke** [fkie-cad/FACT_core#98]
If the plaintext of a password resembles a password hash (i.e. all 13 letters long passwords resemble DES hashes), it is stored in plaintext in the database and the password check does not work (meaning the user can't log in) due to a (intended?) bug in flask-security

possible solution: validate the password beforehand with the same hash identifying function used by passlib and disallow such passwords

**Comment by weidenba** [comment]
this should be fixed in passlib/flask-security

**Comment by weidenba** [comment]
fxied in #98
