### ISSUE TITLE
get err "JSONDecodeError("Expecting value", s, err.value) from None"

### ISSUE THREAD

**Issue by chenjianquan7** [fkie-cad/FACT_core#988]
### Your question

cwe_checker 0.6  return error, why?
![image](https://user-images.githubusercontent.com/26828709/222030102-faf6e05c-3d9e-4457-bf14-8bbf54b9e1da.png)

**Comment by maringuu** [comment]
Please [file a bug report](https://github.com/fkie-cad/FACT_core/issues/new?assignees=&labels=bug&template=bug-report.yml).
